### ISSUE TITLE
Please add an Open Source license to the project

### ISSUE THREAD

**Issue by obscurerichard** [thumbsup/lambda-cloudfront-cookies#3]
Would you consider adding a license file to this project? This would be consistent with good [community practices](http://wiki.opensource.org/bin/Projects/How+to+apply+an+open+source+license+to+your+project) and would allow others to build upon your work with a clear set of rules for what is acceptable.

For maximum compatibility with other free software projects, please consider using MIT license, such as expressed here:

https://opensource.org/licenses/MIT

(replace the copyright statement with your copyright, of course)

**Comment by obscurerichard** [comment]
@rprieto Pretty please with sugar on top adopt the MIT license?

**Comment by rprieto** [comment]
Hi @obscurerichard, sorry I had completely missed this issue. Just added the MIT license :+1:

You might also be interested in https://github.com/thumbsup/aws-private-gallery which takes the core concept of this repo, and adds integration with Cognito for a fully managed login system.

**Comment by obscurerichard** [comment]
Thank you! I'll check out https://github.com/thumbsup/aws-private-gallery too. I have an app that I've been incubating that needs a similar stack to protect its resources...
